---
services:
  boilbot:
    build: .
    container_name: boiler-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data/template_boiling.gif:/app/template_boiling.gif
      - ./temp:/app/temp
      - ./cache:/app/cache